# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the TypeScript source
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json ./
RUN npm install

# Copy source and build
COPY src ./src
RUN npm run build

# Stage 2: Create production image
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy built artifacts
COPY --from=builder /app/build ./build

# Ensure non-root ownership of app files
RUN chown -R node:node /app

# Expose stdio for MCP communication
# Start the MCP server
USER node
CMD ["node", "build/index.js"]
